name: my_flutter_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  # flutter_launcher_icons:
  #   android: "launcher_icon"
  #   image_path: "assets/page-1/images/image-1.png"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  # camera: ^0.10.5+6
  # record: ^5.0.1
flutter_icons:
    android: "launcher_icon"
    image_path: "assets/page-1/images/image-1.png"
    ios: true
   
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: 'Source Sans Pro'
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
        - asset: assets/fonts/SourceSans3-Bold.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/ear.png
    - assets/page-1/images/image-57.png
    - assets/page-1/images/image-48.png
    - assets/page-1/images/image-49.png
    - assets/page-1/images/background.png
    - assets/page-1/images/Illustration.png
    - assets/page-1/images/image-66.png
    - assets/page-1/images/image-51.png
    - assets/page-1/images/image-59.png
    - assets/page-1/images/apple-1.png
    - assets/page-1/images/image-71.png
    - assets/page-1/images/image-74.png
    - assets/page-1/images/image-74-KQY.png
    - assets/page-1/images/image-67.png
    - assets/page-1/images/image-57-EtL.png
    - assets/page-1/images/arrow-down-2.png
    - assets/page-1/images/image-62.png
    - assets/page-1/images/apple-1-gGU.png
    - assets/page-1/images/image-61.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/image-51-Ase.png
    - assets/page-1/images/image-51-rfn.png
    - assets/page-1/images/image-70.png
    - assets/page-1/images/facebook-1.png
    - assets/page-1/images/image-57-Xq6.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/facebook-1-Sx4.png
    - assets/page-1/images/images-placeholder-square.png
    - assets/page-1/images/image-54.png
    - assets/page-1/images/image-55.png
    - assets/page-1/images/image-53.png
    - assets/page-1/images/google-1.png
    - assets/page-1/images/image-49.png
    - assets/page-1/images/image-49-X32.png
    - assets/page-1/images/google-1-PUx.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/subtract-i2g.png
    - assets/page-1/images/image-52.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/image-71.png
    - assets/page-1/images/image-72.png
    - assets/page-1/images/images-placeholder-square-83E.png
    - assets/page-1/images/people-fill.png
    - assets/page-1/images/image-52-oCp.png
    - assets/page-1/images/vector-eRS.png
    - assets/page-1/images/pngtreebusiness-man-avatar8855195-2.png
    - assets/page-1/images/subtract-4FN.png
    - assets/page-1/images/group-10.png
    - assets/page-1/images/group-19.png
    - assets/page-1/images/nav-tab.png
    - assets/page-1/images/pngtreebusiness-man-avatar8855195-1.png
    - assets/page-1/images/swm-icons-duotone-location-1.png
    - assets/page-1/images/subtract-UL4.png
    - assets/page-1/images/image-60.png
    - assets/page-1/images/images-placeholder-square-Uma.png
    - assets/page-1/images/iconly-light-outline-arrow-down-2.png
    - assets/page-1/images/images-placeholder-square-9Qp.png
    - assets/page-1/images/image-48.png
    - assets/page-1/images/image-73.png
    - assets/page-1/images/vector-feC.png
    - assets/page-1/images/vector-Mpx.png
    - assets/page-1/images/image-72.png
    - assets/page-1/images/image-71.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/image-68.png
    - assets/page-1/images/group-20.png
    - assets/page-1/images/group-10-1fA.png
    - assets/page-1/images/images-placeholder-circle.png
    - assets/page-1/images/microphone-on.png
    - assets/page-1/images/image-58.png
    - assets/page-1/images/images-placeholder-circle-31e.png
    - assets/page-1/images/image-65.png
    - assets/page-1/images/subtract-Qkk.png
    - assets/page-1/images/microphone-on.png
    - assets/page-1/images/auto-group-1zay.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
